server:
  port: 8006

spring:
  application:
    name: gateway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    org.springframework.security: DEBUG
    io.jsonwebtoken: DEBUG


  cloud:
    gateway:
      routes:
        - id: microservicio-usuario
          uri: http://localhost:8001
          predicates:
            - Path=/api/usuario/**
            - Path=/api/cuenta/**
        - id: microservicio-monopatin
          uri: http://localhost:8002
          predicates:
            - Path=/api/monopatin/**
            - Path=/api/parada/**
        - id: microservicio-factura
          uri: http://localhost:8004
          predicates:
            - Path=/api/factura/**
            - Path=/api/detallefactura/**
            - Path=/api/tarifa/**
        - id: microservicio-administrador
          uri: http://localhost:8003
          predicates:
            - Path=/api/mantenimiento/**
            - Path=/admin/**
        - id: microservicio-viaje
          uri: http://localhost:8005
          predicates:
            - Path=/api/viaje/**
            - Path=/api/pausa/**
